name: CI/CD Pipeline for E-Commerce Platform

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Setup .NET Core
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0'

      # Restore dependencies
      - name: Restore Dependencies
        run: dotnet restore

      # Build the project
      - name: Build Project
        run: dotnet build --configuration Release --no-restore

      # Run tests
      - name: Run Tests
        run: dotnet test --configuration Release --no-build --verbosity normal

      # Publish the app
      - name: Publish App
        run: dotnet publish -c Release -o publish_output
