# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: CI/CD Pipeline for E-Commerce Platform

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Checkout Code
      uses: actions/checkout@v4

    # Setup .NET Core
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    
    # Install Entity Framework CLI tools
    - name: Install dotnet-ef
      run: dotnet tool install --global dotnet-ef
      
    # Restore dependencies
    - name: Restore dependencies
      run: dotnet restore

    # Build the project
    - name: Build
      run: dotnet build --no-restore

    # Run tests
    - name: Run Tests
      run: dotnet test --no-build --verbosity normal

    # Publish the app
    - name: Publish app
      run: dotnet publish -c Release -o ./publish_output

    # Saving published files to Artifacts
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3
      with:
       name: publish_output
       path: publish_output/
    
    # Deploying Application to Azure
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
       app-name: ECommercePlatform
       slot-name: production
       publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
       package: ./publish_output
      env:
        DOTNET_ROOT: /usr/share/dotnet

    # Apply database migrations
    - name: Apply Database Migrations
      run: dotnet ef database update --connection "$AZURE_SQL_CONNECTION_STRING" --project ./ECommercePlatform/ECommercePlatform.csproj
      env:
       AZURE_SQL_CONNECTION_STRING: ${{ secrets.AZURE_SQL_CONNECTION_STRING }}

   
    
